### ISSUE TITLE
Conversation.setMemory() don't work

### ISSUE THREAD

**Issue by nicolashachet** [RecastAI/SDK-NodeJS#11]
The following code always give the following error : `[Error: Bad Request]`

```
Conversation.setMemory(
    config.get('recastToken'),
    'abc123', // conversation Token
    {
        test: ['a', 'b']
    }
).then(function(res) {
    console.log(res);
}).catch(function(error) {
    console.log(error);
});
```
Tested with Request Access Token and Developer Access Token.

**Comment by MrTraan** [comment]
Hi @nicolashachet ,
The bug here is that you can only set memories on notions that you created on the bot builder pannel of your recast bot page.
Moreover, the value must be a string.
I'll talk with the team so that the error message explains what's going on instead of just returning `Bad Request`, and we'll update the documentation to make it clearer.

Thank you for your feedback!

**Comment by nicolashachet** [comment]
Thank for your reply.

I've tried this snippet with the same result :
(`job` is an existing notion.)

```
Conversation.setMemory(
    config.get('recastToken'),
    'abc123',
    {
        job: 'a'
    }
);
```

**Comment by MrTraan** [comment]
Hi again @nicolashachet ,
I'm really sorry but I gave you an invalid information 😞 
Actually the value of job must be an object, but you can add every information with every type you like in it.
So something like 
```
Conversation.setMemory(
    config.get('recastToken'),
    'abc123',
    {
        job: { value: 'a' }
    }
);
```
Should work.

Again I'm really sorry for misleading you!

**Comment by nicolashachet** [comment]
Ok it works. :)

Thanks for your reactivity.
