### ISSUE TITLE
Quick Replies don't work on Facebook Messenger via Bot Framework 

### ISSUE THREAD

**Issue by mycaule** [RecastAI/SDK-NodeJS#29]
I tried to send this via `message.reply` to the Bot Framework channel on bot connector.

```
{
      type: 'quickReplies',
      content: {
        title: ' ',
        buttons: [
          {
            title: 'Button1',
            value: 'Button1'
          },
          {
            title: 'Button2',
            value: 'Button2'
          }
        ]
      }
}
```

Then on Bot Framework, I configured Skype, Webchat and Messenger. The quick reply **with empty title** correctly showed up on Skype and Webchat but not Messenger.

It looks like empty titles are not allowed on Messenger.

Setting the title to not empty value then shows a Facebook Button Template not a Facebook Quick Reply which is a problem in matters of graphical design. The choices are showed vertically instead of horizontally and there is a limitation of characters.

```
{
      type: 'quickReplies',
      content: {
        title: '...',
        buttons: [
          {
            title: 'Button1',
            value: 'Button1'
          },
          {
            title: 'Button2',
            value: 'Button2'
          }
        ]
      }
}
```

It seems to be a backend problem (call from Bot Connector to Microsoft's API) rather than with the SDK. Sorry I don't know where else to post this.

## References
https://recast.ai/docs/structured-messages
https://developers.facebook.com/docs/messenger-platform/send-messages/template/button
https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies

**Comment by MrTraan** [comment]
Hi Michel,
It doesn't surprise me that facebook rejects quickReplies with empty or "blank characters only" titles, since this field is mandatory, though it's weird that microsoft accepts a space as a valid title.

For your problem with quickReplies vs button template, this is most likely to be an issue from your code.
I use this syntax every day and have never seen this problem before, there would be no reason why the Recast Bot Connector would convert a quickReplies message to a button template.

Could you please make sure that it is the json you were linking that leads to a button template? If so could you please share a snippet of the code that leads to this behavior?

Thanks,

**Comment by dbousque** [comment]
@MrTraan He was referring to Recast's bot connector ->  Microsoft Bot Framework -> Messenger I believe, and not Recast's bot connector -> Messenger :)

**Comment by mycaule** [comment]
Ok the bug is on Microsoft side.
